### ISSUE TITLE
Add import/export for the settings.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tillig/FirefoxNtlmAuth#13]
```
It would be nice to be able to import/export the list of settings for easy 
backup and configuration.

The import/export should include both the list of domains and the "allow 
non-FQDN" setting.

```

Original issue reported on code.google.com by `travis.illig` on 30 Jul 2012 at 3:23

**Comment by tillig** [comment]
Given the add-on is being deprecated by the new plugin model of Firefox where plugins can no longer access browser settings, I'm going to be unable to address this or any other issues. [See the wiki for more details.](https://github.com/tillig/FirefoxNtlmAuth/wiki)
