### ISSUE TITLE
Populate "Add" box with domain of current site

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tillig/FirefoxNtlmAuth#2]
```
When you open the dialog to add a site to the NTLM auth list, populate the text 
box with the domain of the current site being viewed.

```

Original issue reported on code.google.com by `travis.illig` on 10 Jun 2010 at 2:47

**Comment by tillig** [comment]
Given the add-on is being deprecated by the new plugin model of Firefox where plugins can no longer access browser settings, I'm going to be unable to address this or any other issues. [See the wiki for more details.](https://github.com/tillig/FirefoxNtlmAuth/wiki)
