### ISSUE TITLE
Add on bar icon or keyboard shortcut?

### ISSUE THREAD

**Issue by tkls64** [tillig/FirefoxNtlmAuth#25]
Hi. I just got your add-on and it does make things much easier for my company's intranet servers. If I might be so bold as to suggest an improvement, it would be to add a keyboard shortcut or an icon that can be added to the Add-On bar. 
Normally I don't have the menu showing so when I go to a new site, being able to hit a keyboard shortcut and have your add-on pop up with the URL already added would make it truly superb.
Thanks for your consideration!!

**Comment by tillig** [comment]
Given the add-on is being deprecated by the new plugin model of Firefox where plugins can no longer access browser settings, I'm going to be unable to address this or any other issues. [See the wiki for more details.](https://github.com/tillig/FirefoxNtlmAuth/wiki)
